name: Nations
main: com.germancoding.nations.Nations
version: 0.2.1
website: https://www.germancoding.com
author: GermanCoding/Nummer378
commands:
   n:
      description: Nations Hauptkommando
      aliases: [nations, aknmnations, aknm_nations]

