name: Nations
main: com.germancoding.nations.Nations
version: 0.1.0
website: http://www.aknm-craft.de
author: GermanCoding/Nummer378
commands:
   n:
      description: Nations Hauptkommando
      aliases: [nations, aknmnations, aknm_nations]

