package com.germancoding.nations.skills;

public enum SkillType {
	BLUTRAUSCH, TORNADO, PFEILHAGEL, UNSTERBLICHKEIT, SCHUTZ, GOLEMBESCHWÖRUNG, AUSBRUCH_DER_WINDE, INFLAMMATOR, FLY, PREDATOR, EXPLOSION, NACHTDERUNTOTEN;
}
